name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build and push Docker image
      id: build_push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: sarvesh717/stocks
        tags: v3
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-container:
    needs: build-image
    runs-on: ubuntu-latest
    if: ${{ success() }} # ! we only want to deploy if the build was successful
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.SSH_USERNAME}}
        key: ${{ secrets.SSH_PASSWORD }}
        script: |
            echo "Changing to deployment directory..."
            cd Stock-Deployment
            echo "Pulling latest code..."
            git pull origin main
            echo "Stopping existing containers..."
            sudo docker-compose down
            echo "Pulling latest images..."
            sudo docker-compose pull
            echo "Starting containers..."
            sudo docker-compose up -d
            echo "Deployment complete. Listing running containers..."
            sudo docker ps -a
